#!/usr/bin/env bash

set -euo pipefail

MESHTASTIC_TEST_TRANSPORT=tcp \
MESHTASTIC_TEST_TCP_HOST=192.168.1.40 \
MESHTASTIC_TEST_TCP_PORT=4403 \
MESHTASTIC_TEST_TIMEOUT_SEC=45 \
MESHTASTIC_TEST_MUTABLE_CHANNEL_INDEX=2 \
MESHTASTIC_TEST_ENABLE_OWNER_WRITE=true \
MESHTASTIC_TEST_ENABLE_SECURITY_WRITE=true \
MESHTASTIC_TEST_ENABLE_MQTT_WRITE=true \
MESHTASTIC_TEST_ENABLE_REBOOT_TEST=true \
MESHTASTIC_TEST_ENABLE_NODEDB_MUTATION=true \
MESHTASTIC_TEST_ENABLE_NODEDB_RESET=true \
mvn -Phardware-it verify
