#!/usr/bin/env bash

set -euo pipefail

MESHTASTIC_TEST_TRANSPORT=serial \
MESHTASTIC_TEST_PORT=/dev/cu.usbserial-0001 \
MESHTASTIC_TEST_TIMEOUT_SEC=45 \
MESHTASTIC_TEST_MUTABLE_CHANNEL_INDEX=1 \
MESHTASTIC_TEST_ENABLE_OWNER_WRITE=true \
MESHTASTIC_TEST_ENABLE_SECURITY_WRITE=true \
MESHTASTIC_TEST_ENABLE_MQTT_WRITE=true \
MESHTASTIC_TEST_ENABLE_REBOOT_TEST=true \
MESHTASTIC_TEST_ENABLE_NODEDB_MUTATION=true \
MESHTASTIC_TEST_ENABLE_NODEDB_RESET=true \
mvn -Phardware-it verify
